[package]
name = "chess-bot-yolo"
version = "0.1.0"
edition = "2024"

[dependencies]
ab_glyph = "0.2.29"
anyhow = "1.0.98"
arcstr = "1.2.0"
image = "0.25.6"
imageproc = "0.25.0"
ort = "1.16.3"
rusttype = "0.9.3"
xcap = "0.5.1"
yolo-rs = "0.1.2"

